#!/bin/bash

# Describe the build function
function install() {

  # Remove the node modules
  rm node_modules -rf

  # Install the modules from yarn
  yarn install -s

  # Convert the modules to nix
  yarn2nix > yarn.nix

  # Build the modules in nix
  nix-build .nix/modules.nix -o .nix/dist

  # Remove the modules installed by yarn
  rm node_modules -rf

  # Get the current package name
  name=$( cat package.json | jq -r '.name' ) 

  # Link to the modules built by nix
  ln -s $PWD/.nix/dist/libexec/$name/node_modules $PWD/node_modules
}

echo -e "\x1b[34m\x1b[1m[nix-service]\x1b[0m Select your option:\n"

PS3="\nelect the operation: "

select opt in build serve; do

  case $opt in
    build)
      build
      break
      ;;
    serve)
      read -p "Enter the first number: " n1
      read -p "Enter the second number: " n2
      echo "$n1 - $n2 = $(($n1-$n2))"
      ;;
    *) 
      echo "Invalid option $REPLY"
      ;;
  esac
done