#!/bin/bash

# Log out a message
echo -e "\n\x1b[34m\x1b[1m[nix-service]\x1b[0m Installing nix-service..."

# Make the nix folder
mkdir -p .nix

# Make the tools folder
mkdir -p .nix/tools

# Install spastic to the tools
curl -s --compressed  https://codeload.github.com/danzlarkin/spstic/tar.gz/refs/tags/v0.0.2 | tar xvz -C .nix/tools

# Save the nix shell script
curl -s -o shell.nix https://raw.githubusercontent.com/oneislandearth/nix-service/main/nix/shell.nix

# Save the modules shell script
curl -s -o modules.nix https://raw.githubusercontent.com/oneislandearth/nix-service/main/nix/modules.nix

# Save the gitignore
curl -s -o .gitignore https://raw.githubusercontent.com/oneislandearth/nix-service/main/.gitignore

# Log out a message
echo -e "\n\x1b[34m\x1b[1m[nix-service]\x1b[0m Successfully installed and configured\n"